
baseURL = "http://patbrowne.me"
title = "pat browne"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
publishDir = "docs/"

paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[params]
author = "Pat Browne"
description = "Pat Browne's personal website"
keywords = "blog,developer,personal,projects,programs,applications,programming"
info = "Programmer"
avatarURL = "images/profileimage.jpg"
dateFormat = "January 2, 2006"
since = 2022
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Email"
icon = "far fa-envelope"
weight = 0
url = "mailto:pbrowne2@bu.edu"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/pbrowne011/"

# [[params.social]]
# name = "Gitlab"
# icon = "fa fa-2x fa-gitlab"
# weight = 2
# url = "https://gitlab.com/johndoe/"

# [[params.social]]
# name = "Twitter"
# icon = "fa fa-2x fa-twitter"
# weight = 3
# url = "https://twitter.com/johndoe/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/pat-browne/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 
# url = "posts/"