baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Pat Browne"
theme = "ezhil"

publishDir = "docs/"

# Enable syntax highlighting
pygmentsStyle = "solarized-dark"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# Google Analytics tag (add in future
googleAnalytics = ""

# Number of posts to show (recent list)
paginate = 20

# Number of characters to show in summary
summaryLength = 180

[params]
author = "Pat Browne"
subtitle = ""
favicon = "/images/favicon.ico"

# Content types (not sections) to include on front page
# Types I want to use: {"page", "post}
mainSections = ["post"]

# Allow fetching icons from CDN
featherIconsCDN = true

# Mode can be "dark" or "auto"
mode = "auto"


# ---------- Custom site content --------------- #
# # Custom CSS
# customCSS = []
# # Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
# customSCSS = []
# # Custom JS
# customJS = []


[outputs]
home = ["HTML", "RSS"]

# Main menu (below site header)
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[taxonomies]
tag = "tags"


[[params.social]]
name = "Email"
icon = "mail"
#weight = 1
url = "mailto:pjbrowne011@gmail.com"

[[params.social]]
name = "Github"
icon = "github"
#weight = 2
url = "https://github.com/pbrowne011/"

[[params.social]]
name = "RSS"
icon = "rss"
#weight = 3
url = "/index.xml"


# Markdown formatting
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allows rendering of raw HTML in Markdown files
    [markup.goldmark.extensions]
      footnote = true






# [[params.social]]
# name = "Gitlab"
# icon = "fa fa-2x fa-gitlab"
# weight = 2
# url = "https://gitlab.com/johndoe/"

# [[params.social]]
# name = "Twitter"
# icon = "fa fa-2x fa-twitter"
# weight = 3
# url = "https://twitter.com/pbrowne011/"

# [[params.social]]
# name = "LinkedIn"
# icon = "fa fa-2x fa-linkedin"
# weight = 4
# url = "https://www.linkedin.com/in/pat-browne/"

# [[languages.en.menu.main]]
# name = "About"
# weight = 1
# url = "about/"

# [[languages.en.menu.main]]
# name = "Projects"
# weight = 2
# url = "projects/"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 
# url = "posts/"